apiVersion: apps/v1
kind: Deployment

metadata:
  name: static-website
  namespace: default
  labels:
    app: static-website

spec:
  replicas: 2

  selector:
    matchLabels:
      app: static-website

  template:
    metadata:
      labels:
        app: static-website

    spec:
      containers:
      - name: static-website
        image: dockernavaneeth/shapel-website:1
        imagePullPolicy: Always

        ports:
        - containerPort: 80

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10

        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
